server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project_delivery_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '!123456Shao'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: /tmp

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 文件上传配置
app:
  file:
    upload-dir: /Users/shaoliang/Documents/corsor_workplace/data/uploads/

file:
  upload:
    path: /Users/shaoliang/Documents/corsor_workplace/data/uploads/
    allowed-types: pdf,doc,docx,xls,xlsx,ppt,pptx,txt
    max-size: 104857600  # 100MB

# 日志配置
logging:
  level:
    root: info
    com.projectdelivery: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.baomidou.mybatisplus: debug
    org.apache.ibatis: debug
    org.springframework.transaction: debug
    org.springframework.jdbc: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /Users/shaoliang/Documents/corsor_workplace/data/logs/application.log 
    max-size: 100MB
    max-history: 30
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB 